spring.application.name=spring-rest

spring.datasource.url=jdbc:postgresql://localhost:5432/RestAPI
spring.datasource.username=postgres
spring.datasource.password=08192003

spring.jpa.hibernate.ddl-auto=update
